spring.application.name=backend
server.port=8080

# MySQL Workbench Configuration
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/cafedb?createDatabaseIfNotExist=true
spring.datasource.username=cafe_app
spring.datasource.password=cafe123
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Logging
logging.level.org.springframework.security=DEBUG

# Email Configuration (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=shaileshbargal19@gmail.com
spring.mail.password=ddfj qulz bwbu yowb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Razorpay Configuration
razorpay.key.id=rzp_test_SiNcmF0EGPRVVB
razorpay.key.secret=mKpwM9bZAKeSOYabvQUoYWFk
